public class Main {
    public static void main(String[] args) {
        final String RATerminadoZeroOuUm = "BRGTGCGCJKSCNSTVGCRKCNGJXSYBNBG.CKLKCZBGCJKCDBACXKTRKTCPGTBVCXTKNWGVBVCRKCVGZG,CBZBLWVBZRGCJKZVBEKZVCNWDTBRBV.";
        final String RATerminadoDoisOuTres = "IWYCOUDOGVEGCEUZDTOUGWGZEXGNXUYWGVEGNWZJXCONOWGEYCEGYEZEYCUE.GJUWHEYYWU,GNWTCWGNWZGOGYXOGNWQOAWUONOW.";
        final String RATerminadoQuatroOuCinco = "CFTZLOPRFTZLFEXBOFTZGBXIXBOCFTZCVBFPEXZJZNVBTJ,ZTXHVBFPNFZCFZOPIJBLFNFJZPFJZXTEFRZXPEBXZXKFT.";
        final String RATerminadoSeisOuSete = "NMGTBMPYWGJQJDSMSMYWGKMEMSJMWGKBDCRPJGYGSBDWY,GJGJWPJGRCYGEYMGBTGKJVJW.GSYTIVMSCGTCMWGKCGIDYQMTCGNJA,GIDYEJWWYD.";
        final String RATerminadoOitoOuNove = "JINKIYSWHCPSYGPGPSRIAISHSJCMINSWHSPGYGPKAG.SGPRGAHSDXGSGXSQHMPCVISPHOAGBCBGASISKHWIPSIPSWCPQCRNCMIP.";

        Decrypto decrypto = new Decrypto();
        decrypto.recorrenciaQtdeCaractere(RATerminadoZeroOuUm);
    }
}